package com.softgr5.microservicio.viajes.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;



@Getter
@Setter
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "ViajeDestino")
@Builder
@DynamoDBDocument
public class ViajeDestino {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String idviajedestino;

    @DynamoDBAttribute
    private String departamentodestino;
    @DynamoDBAttribute
    private String ciudaddestino;
    @DynamoDBAttribute
    private String direcciondestino;
    @DynamoDBAttribute
    private String paisdestino;
    @DynamoDBAttribute
    private String latituddestino;
    @DynamoDBAttribute
    private String longituddestino;


    public String getIdviajedestino() {
        return idviajedestino;
    }

    public void setIdviajedestino(String idviajedestino) {
        this.idviajedestino = idviajedestino;
    }

    public String getDepartamentodestino() {
        return departamentodestino;
    }

    public void setDepartamentodestino(String departamentodestino) {
        this.departamentodestino = departamentodestino;
    }

    public String getCiudaddestino() {
        return ciudaddestino;
    }

    public void setCiudaddestino(String ciudaddestino) {
        this.ciudaddestino = ciudaddestino;
    }

    public String getPaisdestino() {
        return paisdestino;
    }

    public void setPaisdestino(String paisdestino) {
        this.paisdestino = paisdestino;
    }

    public String getDirecciondestino() {
        return direcciondestino;
    }

    public void setDirecciondestino(String direcciondestino) {
        this.direcciondestino = direcciondestino;
    }

    public String getLongituddestino() {
        return longituddestino;
    }

    public void setLongituddestino(String longituddestino) {
        this.longituddestino = longituddestino;
    }

    public String getLatituddestino() {
        return latituddestino;
    }

    public void setLatituddestino(String latituddestino) {
        this.latituddestino = latituddestino;
    }



    @Override
    public String toString() {
        return "ViajeDestino{" +
                "idviajedestino=" + idviajedestino +
                ", paisdestino='" + paisdestino + '\'' +
                ", latituddestino=" + latituddestino +
                ", longituddestino=" + longituddestino +
                // No incluir 'viaje' para evitar recursión
                '}';
    }
}
