package com.softgr5.microservicio.viajes.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;



@Data
@DynamoDBTable(tableName = "ViajeOrigen")
@Builder
@DynamoDBDocument
@NoArgsConstructor
@AllArgsConstructor
public class ViajeOrigen {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String idviajeorigen;

    @DynamoDBAttribute
    private String departamentoorigen;
    @DynamoDBAttribute
    private String ciudadorigen;
    @DynamoDBAttribute
    private String direccionorigen;
    @DynamoDBAttribute
    private String paisorigen;
    @DynamoDBAttribute
    private String latitudorigen;
    @DynamoDBAttribute
    private String longitudorigen;


    public String getIdviajeorigen() {
        return idviajeorigen;
    }

    public void setIdviajeorigen(String idviajeorigen) {
        this.idviajeorigen = idviajeorigen;
    }

    public String getDepartamentoorigen() {
        return departamentoorigen;
    }

    public void setDepartamentoorigen(String departamentoorigen) {
        this.departamentoorigen = departamentoorigen;
    }

    public String getDireccionorigen() {
        return direccionorigen;
    }

    public void setDireccionorigen(String direccionorigen) {
        this.direccionorigen = direccionorigen;
    }

    public String getPaisorigen() {
        return paisorigen;
    }

    public void setPaisorigen(String paisorigen) {
        this.paisorigen = paisorigen;
    }

    public String getCiudadorigen() {
        return ciudadorigen;
    }

    public void setCiudadorigen(String ciudadorigen) {
        this.ciudadorigen = ciudadorigen;
    }


    public String getLatitudorigen() {
        return latitudorigen;
    }

    public void setLatitudorigen(String latitudorigen) {
        this.latitudorigen = latitudorigen;
    }

    public String getLongitudorigen() {
        return longitudorigen;
    }

    public void setLongitudorigen(String longitudorigen) {
        this.longitudorigen = longitudorigen;
    }

    @Override
    public String toString() {
        return "ViajeOrigen{" +
                "idviajeorigen=" + idviajeorigen +
                ", paisorigen='" + paisorigen + '\'' +
                ", latitudorigen=" + latitudorigen +
                ", longitudorigen=" + longitudorigen +
                // No incluir 'viaje' para evitar recursión
                '}';
    }
}
